name = "watermark-tool"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "watermark-tool-db"
database_id = "7607e1d1-9605-4588-a486-9e7da2cdc749"

[vars]
GOOGLE_CLIENT_ID = "your_google_client_id.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "your_google_client_secret"
